"""Browser UI for exploring the RAG-safety knowledge base via the MCP server.

A small Starlette app (no new dependencies — Starlette + uvicorn already ship
with the ``mcp`` package) that acts as an **MCP client**: it connects to a
running MCP server (``RAGSAFETY_MCP_URL``, e.g. the Azure Container App) and
invokes the tools over the wire, so the output is generated by that server. The
UI lets you flip the caller *persona* and the two ablation axes (chunk
*strategy* and retrieval *mode*), which are forwarded as tool arguments.

Run it with (pointing at a running server)::

    RAGSAFETY_MCP_URL=https://<app>.<region>.azurecontainerapps.io/mcp \\
        python -m ragsafety.webui

then open http://127.0.0.1:8080.
"""

from __future__ import annotations

from .app import build_webui, main

__all__ = ["build_webui", "main"]
