"""Starlette app + JSON API backing the knowledge-base explorer UI.

This explorer is a thin **MCP client**: every tool call goes over the wire to a
running MCP server (``RAGSAFETY_MCP_URL`` — point it at the Azure Container App),
so the output you see is generated by that server, not computed in-process. The
two ablation axes (chunk *strategy* and retrieval *mode*) are forwarded as the
optional tool arguments the server now accepts.

Personas, strategies, modes and the document inventory shown in the UI are local
display metadata (the same ``config/*.yaml`` + ``data/manifest.json`` the server
reads); the actual retrieval, trimming and generation happen server-side.
"""

from __future__ import annotations

import os
from pathlib import Path

from ..security import UnknownPersona, persona_groups
from ..settings import ChunkStrategy, RetrievalMode, get_settings, load_personas
from . import mcp_client

STATIC_DIR = Path(__file__).resolve().parent / "static"

STRATEGY_HELP = {
    "fixed_no_overlap": "Fixed-size token windows, no overlap — cheapest, can split a rule across chunks.",
    "fixed_overlap": "Fixed-size windows with token overlap — fewer boundary misses, more chunks.",
    "section_aware": "Chunks respect document headings/sections — best provenance and citations.",
}
MODE_HELP = {
    "vector": "Dense embedding similarity only (semantic).",
    "bm25": "Classic keyword (BM25) only (lexical).",
    "hybrid": "BM25 + vector fused with Reciprocal Rank Fusion.",
    "hybrid_rerank": "Hybrid + semantic reranker — separates near-duplicate rules (11 kV vs 33 kV).",
}
# Fields the UI should show per tool. (Tool list/summaries come live from the
# server; this just drives which inputs to render.)
TOOL_FIELDS = {
    "get_safety_checklist": ["query"],
    "search_policies": ["query", "top_k"],
    "get_document_section": ["doc", "section"],
}


def _documents() -> list[dict]:
    """Document inventory from the manifest, so the UI can show 'the data'."""
    from ..app import _manifest_meta

    docs = []
    try:
        meta = _manifest_meta()
    except Exception:  # noqa: BLE001 - manifest optional for the UI
        meta = {}
    for m in meta.values():
        docs.append(
            {
                "doc": m.get("doc", m.get("source", "")),
                "domain": m.get("domain", ""),
                "allowed_groups": m.get("allowed_groups", []),
            }
        )
    return sorted(docs, key=lambda d: (d["domain"], d["doc"]))


def _tool_args(tool: str, body: dict) -> dict:
    """Build the MCP tool arguments from a UI request, omitting blanks."""
    persona = (body.get("persona") or "").strip()
    strategy = (body.get("strategy") or "").strip()
    mode = (body.get("mode") or "").strip()
    args: dict = {}
    if persona:
        args["persona"] = persona
    if body.get("groups"):
        args["groups"] = body["groups"]
    if strategy:
        args["strategy"] = strategy
    if mode:
        args["mode"] = mode

    fields = TOOL_FIELDS.get(tool)
    if fields is None:
        raise ValueError(f"unknown tool: {tool!r}")
    if "query" in fields:
        q = (body.get("query") or "").strip()
        if not q:
            raise ValueError(f"query is required for {tool}")
        args["query"] = q
    if "top_k" in fields:
        args["top_k"] = int(body.get("top_k") or 5)
    if "doc" in fields:
        doc = (body.get("doc") or "").strip()
        if not doc:
            raise ValueError(f"doc is required for {tool}")
        args["doc"] = doc
        args["section"] = (body.get("section") or "").strip()
    return args


def build_webui():
    """Return a configured Starlette application."""
    from starlette.applications import Starlette
    from starlette.responses import FileResponse, JSONResponse
    from starlette.routing import Mount, Route
    from starlette.staticfiles import StaticFiles

    settings = get_settings()

    async def index(_request):
        return FileResponse(STATIC_DIR / "index.html")

    async def config(_request):
        personas = load_personas().get("personas", {})
        connection = await mcp_client.server_info(settings)
        return JSONResponse(
            {
                "connection": connection,
                "personas": [
                    {
                        "id": pid,
                        "display_name": meta.get("display_name", pid),
                        "role": meta.get("role", ""),
                        "groups": meta.get("groups", []),
                    }
                    for pid, meta in personas.items()
                ],
                "strategies": [
                    {"id": s.value, "help": STRATEGY_HELP.get(s.value, "")} for s in ChunkStrategy
                ],
                "modes": [
                    {"id": m.value, "help": MODE_HELP.get(m.value, "")} for m in RetrievalMode
                ],
                "tool_fields": TOOL_FIELDS,
                "documents": _documents(),
                "defaults": {
                    "persona": settings.persona,
                    "strategy": settings.chunk_strategy.value,
                    "mode": settings.retrieval_mode.value,
                    "top_k": settings.top_k,
                },
            }
        )

    async def invoke(request):
        import time

        body = await request.json()
        tool = (body.get("tool") or "").strip()
        try:
            args = _tool_args(tool, body)
        except (ValueError, KeyError) as exc:
            return JSONResponse({"error": str(exc)}, status_code=400)

        # Local display metadata (the server resolves identity authoritatively).
        persona = args.get("persona", "")
        try:
            groups = args.get("groups") or (persona_groups(persona) if persona else [])
        except UnknownPersona:
            groups = []

        started = time.perf_counter()
        try:
            result = await mcp_client.call_tool(settings, tool, args)
        except mcp_client.MCPClientError as exc:
            return JSONResponse({"error": str(exc)}, status_code=502)
        elapsed_ms = round((time.perf_counter() - started) * 1000, 1)

        return JSONResponse(
            {
                "tool": tool,
                "elapsed_ms": elapsed_ms,
                "source": settings.mcp_url,
                "identity": {"persona": persona, "groups": groups},
                "effective": {
                    "strategy": args.get("strategy", settings.chunk_strategy.value),
                    "mode": args.get("mode", settings.retrieval_mode.value),
                    "top_k": args.get("top_k"),
                },
                "arguments": args,
                "result": result,
            }
        )

    routes = [
        Route("/", index),
        Route("/api/config", config),
        Route("/api/invoke", invoke, methods=["POST"]),
        Mount("/static", StaticFiles(directory=STATIC_DIR), name="static"),
    ]
    return Starlette(routes=routes)


def main() -> None:
    import uvicorn

    host = os.environ.get("RAGSAFETY_WEBUI_HOST", "127.0.0.1")
    port = int(os.environ.get("RAGSAFETY_WEBUI_PORT", "8080"))
    print(f"RAG Safety Explorer -> MCP server at {get_settings().mcp_url}")
    print(f"Open http://{host}:{port}")
    uvicorn.run(build_webui(), host=host, port=port, log_level="warning")


if __name__ == "__main__":
    main()
